### ISSUE TITLE
macOS: the current working directory is /, rather than the user's home directory

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#108]
Start APL/RIDE on macOS
      )SH pwd
/

IDE:
  Version: 4.0.2679
  Platform: MacIntel
  Date: 2017-03-01 19:10:37 +0000
  Git commit: c359f660447dce9b29195939a3a6a052af6cedac
  Preferences:{

  }

Interpreter:
  Version: 16.0.29355
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  2 2017 at 02:32:24

**Comment by jayfoad** [comment]
Jay's diagnosis:

1. On the Mac, when you click on an application like RIDE, the system seems to start it with / as the current working directory (cwd).
2. When RIDE spawns an interpreter, the new process inherits the cwd of its parent.

Possible solutions:

1. Get RIDE to change its own cwd to $HOME as it starts up.
2. Get RIDE to set the cwd of any interpreter it spawns to $HOME.

But neither of these feel quite right to me, because if I start RIDE from the command line (e.g. on Linux) and spawn an interpreter, I might reasonably expect that the spawned interpreter is running in the same directory that I started RIDE from.

So, I propose to add a new "working directory" option when you spawn an interpreter. The field will be prefilled with the value of $HOME, but you can set it to anything you like, including "" (empty) to inherit RIDE's own cwd.

**Comment by JasonRivers** [comment]
This sounds like a good solution.

In the UI, Please could you expand $HOME, though. As a user - I might have no idea what $HOME means, but I know exactly what /Users/Jason (macOS) or /home/jason (Linux) is.

**Comment by jayfoad** [comment]
There's still a problem: when you start RIDE with RIDE_SPAWN=dyalog, you don't get a chance to set the working directory, so it still defaults to / on the Mac.

**Comment by jayfoad** [comment]
The intent of those commits is:

1. For developers, if you run RIDE from the command line, and RIDE spawns an interpreter, the interpreter will be running in whatever your current directory was in the first place.

2. If you run an installed RIDE it'll be running in your home directory (at least on the Mac; not sure about other platforms yet) so any spawned interpreter will also run in your home directory.

3. In both cases you can override the working directory of the interpreter by filling in a field on the connect page, giving an absolute or relative path. The field defaults to '' (empty string) which just means wherever RIDE is running.
