### ISSUE TITLE
In certain scenarios, the default Exe is not show at the top

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1140]
### Describe the issue you are having
This might be happening because I installed 20.0 after RIDE 4.5:
![image](https://github.com/Dyalog/ride/assets/10961427/0986a885-5229-48e3-b8c4-df37bbd535bb)
Note how the <kbd>MAKE DEFAULT</kbd> button is grey, i.e. 20.0 is the default, but 19.0 is shown in large at the top.
```
4.5.3999
```

**Comment by e9gille** [comment]
Installing new versions shouldn't automatically set them as default, so I assume you set it as default after installing it. There was a bug in that clicking the "Make Default" didn't save the state (fixed in #1155) , so that might explain what you see.
Feel free to re-open if you can replicate this.
