### ISSUE TITLE
Editor removes my leading blanks

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#156]
### Describe the issue you are having
In an edit window, hitting enter in the left margin removes any leading blanks.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start
### How do you reproduce the issue?
<pre>
      )ed →cvec
in the edit window, type four blanks, followed by "hello"
move the cursor to the left margin and hit Return.
The "hello" moves down to the next line but my indentation has disappeared.
</pre>
Notepad, ODE, textedit, ... preserve my blanks in this situation.
Happily, typing a **backspace** in the left margin, correctly joins any following text to the previous line **and** keeps my blanks.
### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2789
  Platform: MacIntel
  Date: 2017-04-25 11:38:17 +0100
  Git commit: 5700c3d8548a2be5313b4984193dada0dbc50521
  Preferences:{
    "autocompletion":"0",
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "valueTips":"0",
    "zoom":"6"
  }

Interpreter:
  Version: 16.0.29826
  Platform: Mac-64
  Edition: Unicode/64
  Date: Apr 27 2017 at 02:30:17

**Comment by ngn** [comment]
The fix for this one is a bit tricky.
`cm.setOption('smartIndent',false)` would still make the new line copy the previous line's indent, though not in a "smart" way. Technically, that works [as documented](https://codemirror.net/doc/manual.html#option_smartIndent).
The way I would work around it is make [&lt;ER>](https://github.com/Dyalog/ride/blob/master/src/ed.js#L208) check the editor's mode, and if it's not APL, do `cm.replaceSelection('\n','end')` instead of `cm.execCommand('newlineAndIndent')`.

It might also be worth [chatting with Marijn and contributors](https://discuss.codemirror.net/) about `smartIndent`'s documented vs expected behaviour.

**Comment by e9gille** [comment]
thanks @ngn , will put in your suggestion
