### ISSUE TITLE
Editor: multi-line selection highlights beyond end of lines

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#175]
### Describe the issue you are having
Multi-line selection highlights whole width of window.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter 

### How do you reproduce the issue?
<pre>
      mat←3 3⍴3/'abc'
      )ed mat
     ⍝ now type Cmd+a or Ctrl+a to select all
</pre>

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2834
  Platform: MacIntel
  Date: 2017-06-20 13:42:27 +0100
  Git commit: 2d04452b43978e397de5f1131b0252560523ae3c
  Preferences:{
    "autocompletion":"0",
    "fold":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "valueTips":"0",
    "zoom":"5",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.30211
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 23 2017 at 02:31:38

**Comment by jayfoad** [comment]
Don't you like it? This is the standard behaviour of the codemirror editor component we use (see the "This is CodeMirror" example [here](https://codemirror.net/)).

On Linux I get the same kind of highlighting behaviour in terminal windows, and in Emacs, so I'm used to it.

**Comment by JohnScholes** [comment]
It seems daft to me. 
Why's it highlighting characters that aren't there?
Why the inconsistency with the final line?
However, if this is the way you kids like it, or it's hard to fix, feel free to close the issue.
Bah, humbug

mat←3 3⍴⎕a ⋄ ⎕ed'mat' ⍝ Cmd+a to select all:

**Comment by jayfoad** [comment]
> It seems daft to me.
> Why's it highlighting characters that aren't there?

It's giving you a visual indication that you've selected the newline character at the end of the line. When I've selected the text "sudo rm -rf /" and I'm about to copy and paste it into a terminal window, I like to know whether the selection includes a terminating newline or not.

Some systems, like the web page I'm typing into now, tell you that you've selected the newline by highlighting a single non-existent space character at the end of the line, instead of the whole of the rest of the line.

> Why the inconsistency with the final line?

It's just showing you the inconsistency in what you've selected: you haven't selected the newline at the end of the final line. If you selected the text with a mouse, perhaps you should've kept dragging the pointer to just to the left of the start of the following line?

**Comment by JohnScholes** [comment]
Okay.

I prefer the way that the ODE (and MS notepad) does its SelectAll. However,  I accept that
[a] Other people's preferences differ,
[b] It's probably a hassle for the Ride guys to change, 
[c] Nitpicks are swamping the issues list, so should be culled.
John

**Comment by jayfoad** [comment]
I had forgotten that you were talking about SelectAll. I agree it's a shame that the result of SelectAll looks inconsistent in this case, but I don't know how to fix it. Sorry.
