### ISSUE TITLE
TAB key is ignored if there are non-blank chars to its left

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#194]
### Describe the issue you are having
Tab <TB> seems to work in both the session and editor unless there are any non-blank characters to the left of the input cursor. 

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
In the session or an edit window:
   \<TAB>\<TAB> ...   ok
hello \<TAB>\<TAB> ... tabs ignored

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: MacIntel
  Date: 2017-06-27 12:41:03 +0100
  Git commit: 3b6edbed33b247a6072244b5c19a4b3e094eaba4
  Preferences:{
    "autocompletion":"0",
    "fold":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "valueTips":"0",
    "zoom":"9"
  }

Interpreter:
  Version: 16.0.30261
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 27 2017 at 13:01:47

**Comment by jayfoad** [comment]
I think this is intentional, but I guess you don't like it. Originally TAB was only used for autocompletion, then later (63a6ef66946f24fc3792cd578b8a87aac6c7c45f) it was made to indent but only at the start of a line.

However... I'm not sure that TAB does anything useful for autocompletion any more. All it seems to do is let you navigate up and down the pop-up list of autocompletions, but you can do that more naturally with the up and down arrow keys.

**Comment by JohnScholes** [comment]
> ... but only at the start of a line.
> 

Seems a bit of an arbitrary restriction. Plus, that's not quite right. The TAB key works anywhere on the line unless there is a non-blank character anywhere to its left.

TAB for autocompletion is (IMHO) cool, but normally it activates only if there is a non-blank character immediately to the left of the input cursor.
