### ISSUE TITLE
Action->Strong interrupt is ignored

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#195]
### Describe the issue you are having
Weak interrupt is OK but Strong interrupt is ignored.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
<pre>
      {∇⍵}0    ⍝ loops indefinitely: try Action->Strong interrupt
</pre>
### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2859
  Platform: MacIntel
  Date: 2017-07-14 16:15:34 +0100
  Git commit: 0d063161732c819c1f627aa61adb8a0b48fe41db
  Preferences:{
    "autocompletion":"0",
    "fold":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "zoom":"6"
  }

Interpreter:
  Version: 16.0.30372
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jul 17 2017 at 02:49:04

**Comment by jayfoad** [comment]
On Linux I'm seeing the opposite! Weak interrupt should work but doesn't; strong interrupt does work.

**Comment by jayfoad** [comment]
> On Linux I'm seeing the opposite! Weak interrupt should work but doesn't

This is because the RIDE (Electron) process ignores SIGINT, and a spawned interpreter inherits that setting, and interpreters deliberately do not un-ignore any signals that were being ignored. Unfortunately the interpreter responds to a RIDE WeakInterrupt message by sending itself SIGINT, which is then ignored... We have seen similar things before when an interpreter is started by a non-login shell; see Mantis 14141.

**Comment by jayfoad** [comment]
On, the Mac, with RIDE 4.0 or 4.1 and interpreter 16.0 or 17.0, neither weak nor strong interrupt work.

**Comment by jayfoad** [comment]
Fixed in interpreter version 17.0.31131.
