### ISSUE TITLE
Can set breakpoints on a variable

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#197]
Edit a variable:
```
      a←9 9⍴⎕A
      )ed a
```
Click somewhere in the left hand margin of the edit window, or on one of the line numbers like `[3]`. A red dot appears in the margin indicating a breakpoint. You shouldn't be able to set breakpoints in variables, only in functions.

**Comment by e9gille** [comment]
fixed in branch [iss197](https://github.com/Dyalog/ride/tree/iss197)
Also tried adding in options to toggle visibility of gutter columns (request from @JohnScholes). These are currently under the View menu. Let me know what you think.

There is an outstanding issue related to floating windows (toggling gutter items not reflected properly on hidden windows). I'll get that resolved before merging with master.
