### ISSUE TITLE
Preference dialogue box is obscured by floating windows

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#278]
### Describe the issue you are having
If you bring up the preferences dialogue box it remains on top of the session, as it should. However, if you have floating windows, these sit on top of it. This is particularly problematic if the floating windows are "always on top". The preferences box should be on top of everything else.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Open a floating window and make it "always on top". Open preferences. The preferences dialogue box opens behind the floating window.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2931
  Platform: Linux x86_64
  Date: 2017-10-19 07:03:44 +0200
  Git commit: e84f86990bc2d885af4b2dbf19db0d6cc765a28f
  Preferences:{
    "dbg":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31268
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 23 2017 at 17:10:43

**Comment by jayfoad** [comment]
> Open a floating window and make it "always on top".

I think the problem here is that you're using your OS (via a context menu on the window's title bar) to make the window "always on top". This probably means that RIDE has no chance to make its preferences window be even-more-on-top. You should use the "View -> Editors on Top" option instead.

**Comment by JasonRivers** [comment]
I'm not sure about this. Even if RIDE triggers floating windows being on top (which isn't currently working), Because the preferences is always embedded within the main ride window (instead of a separate window) the preferences will be behind the editor unless you stop the editor from being on top while using the preferences. Having the preferences open in a separate window would be very useful for this, but it needs to not be a separate window when using RIDE from a browser.

This is also something I have run in to trying to move the preferences window out of the way to see what the changes look like, it's restricted to the main window, so I can't fully move it out of the way.

**Comment by e9gille** [comment]
what @JasonDyalog  said. We need to open the preferences in a separate window for that to work.

**Comment by DyalogRichard** [comment]
Renamed and reopened per comments from JR and GA

**Comment by DyalogRichard** [comment]
Ok, there's a button to reopen this, but I don't seem to have permission to actually do it. Could someone who does, do so?

**Comment by e9gille** [comment]
I have created a floating preference window that should stay on top of the session. I need to explore how to make it stay on top of other floating editors, but it should be one step closer to something useful.
Try it out in branch [iss278](https://github.com/Dyalog/ride/tree/iss278)
