### ISSUE TITLE
)sh sh hangs

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#313]
### Describe the issue you are having
Using )sh to call an interactive program hangs Ride.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an interpreter

### How do you reproduce the issue?
      )sh sh
or
      )sh bc

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2985
  Platform: MacIntel
  Date: 2017-11-23 09:40:58 +0100
  Git commit: 2dddc0ebbb7fa89cc9fd7e83e03e1f5398b3baec
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "breakPts":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":1082,\"height\":593,\"x\":358,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31693
  Platform: Mac-64
  Edition: Unicode/64
  Date: Dec  2 2017 at 04:06:57

**Comment by JasonRivers** [comment]
This is because when you run )sh you're no longer really in Dyalog, you're in a shell, as Dyalog is in the background and invisible to you you have no way of interacting with the shell that has spawned.
I don't know that there's an easy solution to this, as I don't know how Dyalog handles input/output when a shell is spawned, running a script is fine, though as long as the script returns.

```
      )sh ~/bin/test.sh
/home/jason/bin
this is a test
```
At least at the moment, if you wish to use a shell, I recommend opening a terminal on your Mac.

**Comment by JohnScholes** [comment]
I understand. The problem is that ")sh ls"; ")sh pwd"; etc are very handy. But you have to be careful not to call something that will read stdin, else you lose all your work.

**Comment by abrudz** [comment]
Unfixable.
