### ISSUE TITLE
Search/Replace bar covers topmost line

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#32]
Search/Replace bar covers the topmost line of the frame it appears in.

This is especially confusing if a match is found on the covered line.

**Comment by jayfoad** [comment]
This isn't usually a problem because as soon as you hit ENTER to do the search, the bar disappears. And clicking elsewhere in the editor window also closes the search bar.

However, sometimes it seems to get confused and leave the bar visible even though focus is back in the editor window. Here's a simple repro:
1. )ed foo
2. Ctrl-F (opens search bar)
3. Click the "Search for next match" button (puts focus back in editor window, behind the search bar which is still visible)

**Comment by dyaandys** [comment]
It's more of a problem if you are replacing text.  Consider
∇foo;isandy;andy;andyright
andy
∇
now replace andy with fred; I only want to replace "andy" in the top line, not the other two .. but I can't see what yes and no are referring to.  

With a narrowish editor it is possible to get the search/replace bar to cover lines [0] and [1].

**Comment by jayfoad** [comment]
I reckon the easiest way to fix this is to put the search bar at the bottom of the editor instead of at the top.

CodeMirror's "search" addon uses the "dialog" addon, which already has support for putting the dialog at the bottom. Unfortunately the "search" addon doesn't expose this option, so maybe we'll have to fork it or something...
