### ISSUE TITLE
How to clear all function stops?

### ISSUE THREAD

**Issue by norberturkiewicz** [Dyalog/ride#335]
### Describe the issue you are having
The Windows IDE has an option to clear all stops under the "Action" menu.  How is this accomplished in Ride?  If you can't, I'd like to submit this as a RFE.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2938
  Platform: Win32
  Date: 2017-10-20 11:26:37 +0100
  Git commit: ce6702217f56f7bc543951a8a318b6acf2904b06
  Preferences:{
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 16.0.32456
  Platform: Linux-64
  Edition: Unicode/64
  Date: Mar 13 2018 at 03:31:46

**Comment by jayfoad** [comment]
There is currently no way to do this in RIDE. There is a protocol message to clear all stops for a particular trace window, but RIDE doesn't currently use it. There is no protocol message to clear all stops in the whole workspace.

**Comment by mkromberg** [comment]
It would be good to put this (adding the protocol message) on the short list of RFE's, this is a common requirement - especially when debugging server processes - which is a very typical use case for RIDE. I needed it yesterday, in fact.

**Comment by jayfoad** [comment]
I've discussed this with @johndaintree.

The ODE has two things:
1. A \<CB> keystroke which clears all trace/stop/monitor bits for function currently being edited. (This doesn't appear in the ODE Options->Configure...->"Keyboard Shortcuts" probably because it was deemed mostly useful for TTY versions.)
2. A "Clear Stops" menu item which clears all trace/stop/monitor bits in the workspace.

(1) could be implemented entirely in RIDE. The updated trace/stop/monitor bits will be sent back to the interpreter the next time the function is fixed.

For (2) we can revive and re-purpose the ClearTraceStopMonitor protocol message. It won't need the "win" parameter.

**Comment by jayfoad** [comment]
@e9gille I've changed the protocol ClearTraceStopMonitor message to clear all trace/stop/monitor bits in the whole workspace. (It was previously unused by RIDE and unimplemented in the interpreter.) This'll be in interpreters from 17.0.32850 onwards.

**Comment by e9gille** [comment]
@jayfoad Thanks, I'll build the RIDE side of that now. Let me know when new images of the interpreter are available.

**Comment by e9gille** [comment]
This is now in master branch but currently only supported by v17. Would be good if it can be backported to at least v16 as well.

**Comment by e9gille** [comment]
Closing this as fix in master. @norberturkiewicz if you want it supported on pre v17 please shout.
