### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#38]
It might be nice if RIDE had a status bar at the bottom, like the classic Windows Dyalog IDE, telling you the current workspace, current values of ⎕IO and ⎕ML etc.

**Comment by jayfoad** [comment]
Could be implemented with extra fields in the SetPromptType message.

**Comment by e9gille** [comment]
status bar added in cd23796bded61819dd08e0d8d5efa6552c72acb8
now just waiting for protocol change to receive status information.

**Comment by abrudz** [comment]
This looks amazing!

A couple of points:
1. In a *floating editor window*, the status bar does not change font size with the rest of RIDE. (Btw, the floating edit window language bar doesn't scale either.) 

2. The floating editor's status bar has residual `⎕SI` and `&` fields.

3. It draws attention when moving from a line or column 9 to 10 because the entire status bar jumps to the left to accommodate the additional digit. Maybe reserve space for as many digits as the currently edited item requires?

**Comment by jayfoad** [comment]
Can we have a preference (or View menu item) to disable the status bar please?

**Comment by e9gille** [comment]
Merged in with #685
