### ISSUE TITLE
Pressing <ctrl+cursorLeft> should move the cursor to the previous word (Windows)

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#444]
Given this: `abc←123↓n`

* Pressing `<ctrl+cursorLeft>` with the cursor positioned at the end of the line jumps to the beginning of the line rather than to the left of `n`.

* Pressing `<ctrl+cursorRight>` with the cursor positioned at the beginning of the line jumps to the end of the line rather than to the right of `abc`.

I just realize that selecting via the keyboard does not work correctly either (`<ctrl+shift+cursorRight>` and `<ctrl+shift+cursorLeft>`.

**Comment by e9gille** [comment]
Please bear in mind that some shortcuts differ between platforms due to convention. When reporting issues with shortcuts, please report what you think it should do and on what platform.

On MacOS the default for those shortcuts is to navigate between spaces.

On Windows it should navigate words, but as you point out, it doesn't recognise the primitives as word separators.
