### ISSUE TITLE
F1 works differently in ODE and Ride

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#449]
Pressing F1 in this

```
=≠
```
with the cursor positioned between the `=` and the `≠` has different results in the ODE and Ride:

* The ODE shows the help page for `=`
* Ride shows the help page for `≠`

**Comment by e9gille** [comment]
Now change your prefs to use a block cursor and you will understand why.

I think you may still argue it should show the help for the character to the left, but it isn't as obvious.

**Comment by aplteam** [comment]
I am not arguing with any of this. As long as the two behave the same;)

**Comment by e9gille** [comment]
and your preference?

**Comment by aplteam** [comment]
No pref at all.

**Comment by DyalogRichard** [comment]
The ODE has a "destructive" edit mode (instead of "insert") whereby placing the cursor between two characters and typing a third overwrites the second with the third rather than insert it between the first and second. When in this mode the cursor changes to an underscore yet F1 help gives help for the character to the left of the character the cursor is flashing underneath. I think, therefore, that if it's a straight choice between showing the character to the left or the right, we have good precedence for left even with a block cursor.

However, there is good cause, I think, to ask the following questions:

* Although established behaviour, should we consider "fixing" the ODE? It seems very odd that if I have

⍳⍴

with a flashing underscore cursor underneath the ⍴, F1 help gives help for ⍳.

* Should RIDE have an option to select a block cursor? It would be useful to have that available for a destructive edit mode.

**Comment by dyaandys** [comment]
“should we consider "fixing" the ODE”

No.

 

I would argue that almost no-one has insert mode turned off for more than a few moments if ever; either because they’re attempting to create an overstrike, or because they’ve “hit” the insert toggle by mistake.

 

 

A

**Comment by aplteam** [comment]
I fully agree with Andy: overwrite does not matter these days. I don't do overstrikes; that makes 99% of my destructive modes accidents.

**Comment by abrudz** [comment]
When we get to this, let's have a look at what other editors do.

**Comment by abrudz** [comment]
Can't repro
