### ISSUE TITLE
Edit window > Search bar > Find field > confusing "match whole word" option

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#458]
### Describe the issue you are having
Edit window > Search bar > Find field offers a filter of "match whole word". This is very confusing with APL. As far as I can tell, a word is defined as delimited by spaces or any of the characters (){}[];:,. which doesn't really make sense from an APL perspective. I believe it would be less confusing to a user to remove this option.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
irrelevant

### How do you reproduce the issue?
Edit window > Search bar > Find field. Play with the "match whole word" filter.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3353
  Platform: Win32
  Date: 2018-06-15 21:21:46 +0200
  Git commit: fd94d5676e955ec67cf10c19902a10b15eeaa7f8

Interpreter:
  Version: 17.0.33293
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jun  3 2018 at 20:03:03

**Comment by DyalogRichard** [comment]
I would imagine that having the option, without it understanding APL semantics, is better than not having it at all.

The exact same problem came up with the ODE recently (which switched to using PCRE rather than a bespoke search engine) - http://mantis.dyalog.com/view.php?id=15422. The solution was to search without any "match whole word" option and then to check and, if necessary, discard matches that did not conform (if text precedes or follows it must be a non-APL word char; the match itself must consist only of APL word chars).

**Comment by dyaandys** [comment]
.. and it’s quite important that Quad is considered as part of a word .. we even achieved that on the forums ..

**Comment by e9gille** [comment]
The list of word separators has been improved and now includes all primitives (except for `⎕`) plus the following:
```
()[]{}%£#;:'"`$^
```
