### ISSUE TITLE
Alt+Shift+{I,A,F} doesn't insert characters in mac

### ISSUE THREAD

**Issue by kritixilithos** [Dyalog/ride#465]
### Describe the issue you are having

In attempting to type `⍸`, I press Alt+Shift+I (using the Dyalog keyboard layout) in the repl but no character is typed. I have found out that Alt+Shift+A and Alt+Shift+F also don't work (supposed to type `Å` and `Ï` respectively). This also happens with other keyboard layouts to some extent (for example in the Russian keyboard layout I can type Alt+Shift+A (types `d`) fine, but the others still don't work).

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Start an interpreter

### How do you reproduce the issue?

Open Ride, and in the repl I press Alt+Shift+I

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.2.451
  Platform: MacIntel
  Date: 2018-06-22 11:54:16 +0100
  Git commit: 7a9d5d6a31fead8a4b6ac302dd0759ec8b1f5b64
  Preferences:{
    "colourScheme":"Francisco Goya",
    "editWins":"{\"width\":800,\"height\":600,\"x\":479,\"y\":266,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "kbdLocale":"en_US_Mac",
    "keys":"{\"FX\":[\"Ctrl-S\"],\"JSC\":[\"F12\",\"Shift-Cmd-I\"],\"SI\":[\"Ctrl-D\"],\"WI\":[\"Ctrl-C\"]}",
    "selectionHighlight":"1",
    "squiggleTips":"1"
  }

Interpreter:
  Version: 16.0.31812
  Platform: Mac-64
  Edition: Unicode/64
  Date: Dec 20 2017 at 02:58:16
```

**Comment by JohnScholes** [comment]
Same here. I have the Mac Dyalog Alt UK keylayout installed. Alt+Shift+I gives me ⍸ in other apps (such as this) but no longer in Ride. It used to work.

**Comment by e9gille** [comment]
I've looked into this and found that it is caused by the default key bindings of the editor.
⇧⌥I Insert cursor at end of each line selected
⇧⌥A Toggle block comment
⇧⌥F Format document

See complete list of [mac keyboard shortcuts](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf) in Monaco/VS Code.

All these default shortcuts are undocumented. We should either add them to the documentation (@FionaDyalog) or disable them (@jayfoad). Maybe we only need to disable the ones that may conflict with the Dyalog keyboard layout?

**Comment by jayfoad** [comment]
> Maybe we only need to disable the ones that may conflict with the Dyalog keyboard layout?

That gets my vote.
