### ISSUE TITLE
Output of NULL loses information

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#492]
### Describe the issue you are having
Output of a character vector containing a null causes all output to be lost.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
```apl
      ⎕UCS 65 66 67
ABC
      ⎕UCS 65 66 67 0 ⍝ No output at all
```
### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3333
  Platform: Win32
  Date: 2018-06-07 11:32:16 +0100
  Git commit: 4ef9f066f2ee49dddbff80f37eeb144995c20e43
  Preferences:{
    "kbdLocale":"en_GB",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1",
    "zoom":"3"
  }

Interpreter:
  Version: 17.0.34514
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct  4 2018 at 01:45:00
```

**Comment by e9gille** [comment]
Tested this and can see that the output is wiped on the RIDE side. The reason is that the text provided by the interpreter is not terminated with a new line. I believe this should be fixed on the interpreter side as it truncates the string at null before sending it to RIDE (null terminated string). Can you log it in Mantis please.

**Comment by e9gille** [comment]
Another example with a null mid string (extract from RIDE log):
```
3936646 send ["Execute",{"trace":0,"text":"      ⎕ucs 65  66 0 65 66\n"}]
3936654 recv ["EchoInput",{"input":"      ⎕ucs 65  66 0 65 66\n"}]
3936667 recv ["SetPromptType",{"type":0}]
3936670 recv ["AppendSessionOutput",{"result":"AB"}]
```

**Comment by mkromberg** [comment]
Logged in Mantis as 0016519: Output of NULLs to RIDE leads to lost output

**Comment by DyalogRichard** [comment]
I have updated the interpreter to use Modified UTF-8 encoding. This is exactly the same as UTF-8 except for the value 0 which encodes as 0xC0 0x80. A UTF-8 decoder should decode that back to 0 but it's not technically valid UTF-8 because it's not the shortest possible encoding of 0. On the other hand, it allows the interpreter and RIDE to include U+0000 in null-terminated strings.

Gil - can you work with this? Using the example in this report I now see output with two question marks - those _two_ question marks suggest the UTF-8 decoder has not decoded this as 0.

**Comment by jayfoad** [comment]
UTF-8 decoding is done (very subtly) by this line: https://github.com/Dyalog/ride/blob/81d6ae270e316dcfdf666a157c1e8709c4b4cabd/src/cn.js#L226
and although you could specify a decoder like 'utf8' or 'ascii' I can't see an easy way to decode "Modified UTF-8". So it would be much nicer if the interpreter could just send a 00 byte.

**Comment by jayfoad** [comment]
The fix for this really belongs in the interpreter, so at @DyalogRichard's suggestion I'm closing this RIDE issue.
