### ISSUE TITLE
Comments about configuration list

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#506]
1. It appears that the default configuration (ie the one that is loaded when RIDE is started) is the oldest configuration (or perhaps the one whose name changed longest ago).  How about either letting me set the default one, or starting/highlighting the most recently used one instead ?
2. The order of the list seems "odd" .. for me I have "p8-72qa" "debian7dev" "Local" ..  

IDE:
  Version: 4.2.3389
  Platform: Win32
  Date: 2018-11-24 00:46:44 +0100
  Git commit: dbb5f3c4296c1e3e19b95903cf40e124d06ac4eb
  Preferences:{
    "connectFav":"1",
    "kbdLocale":"en_US",
    "sbar":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by e9gille** [comment]
1. The most recently launched configuration is the one that is pre-selected on launch. It currently does so by saving the index rather than by name, so if you re-order the list it will get it wrong.

1. The order is decided by you, just drag and drop to re-order. New items are just added to the bottom of the list.

**Comment by e9gille** [comment]
@dyaandys can you confirm if you don't see the behaviour I described above?
