### ISSUE TITLE
Add a Close All Windows menu item

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#51]
Add a "Close All Windows" menu item, perhaps on a new "Window" menu, to close all open editors tracers etc.

**Comment by flouc001** [comment]
@jayfoad I'm assuming you want to terminate the connection and close the main RIDE window also?

**Comment by e9gille** [comment]
@flouc001 I don't think he means the main window would be closed, only editors, trace and perhaps wse. Once we add a threads window that would presumably also need to be closed.

**Comment by e9gille** [comment]
The menu option closes all editor and trace windows, but I can see that the behavior differs to ODE with regards to closing the trace window. In ODE that keeps the stack, in RIDE it cuts the stack.

In ODE, closing the trace window with the X cuts the stack, but using the menu option doesn't. What is the expected behavior?

**Comment by jayfoad** [comment]
Needs a protocol message that RIDE can send, saying either:
- close a window (but don't cut the stack), or
- close all windows (but don't cut the stack).
