### ISSUE TITLE
Closing RIDE causes spawned interpreter to drop CONTINUE.dws

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#59]
If I run RIDE and spawn a local interpreter, then close RIDE (by clicking on the X in its window decoration) the interpreter drops a CONTINUE.dws workspace. I think this means it has not been shut down cleanly enough.

Possibly related to #46.

**Comment by jayfoad** [comment]
RIDE should send a Disconnect message to the interpreter.

**Comment by e9gille** [comment]
The fix for #46 included sending a Disconnect before closing down, but I still get a CONTINUE.dws. Tried adding a timeout as well in case the interpreter needed more time without luck.
@johndaintree is the Disconnect handled on the interpreter side? Are you expecting a particular message to go with it?

It seems to work on win, but not osx. Haven't tested linux.

**Comment by e9gille** [comment]
Callum confirms it is a problem on linux as well.

**Comment by flouc001** [comment]
Seems to be fixed for me when using Linux.

IDE:
  Version: 4.0.2674
  Platform: Linux x86_64
  Date: 2017-02-28 16:38:33 +0000
  Git commit: be82c4fa28dfc324748684431d47c6d8a5e79877
  Preferences:{
    "dbg":"1",
    "indentOnOpen":"0",
    "kbdLocale":"en_GB",
    "keys":"{\"RD\":[\"Shift-Ctrl-F\"]}",
    "selectedExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "sqp":"0"
  }

Interpreter:
  Version: 16.0.29373
  Platform: Linux-64
  Edition: Unicode/64
  Date: Mar  2 2017 at 16:17:41
