### ISSUE TITLE
Contextmenu of tree should provide option to delete object

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#69]
It only has Cut/Copy/Paste - but Delete would be equally useful.

**Comment by e9gille** [comment]
I don't think the context menu ever actually had any effect on the workspace explorer tree. The menu has since been removed altogether. We've discussed whether or not to implement any of the operations and decided against it.
I'll close this issue, but if you think it is an important feature please argue your case and convince @jayfoad .
