### ISSUE TITLE
Editor should provide option to reformat source

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#78]
As ODE did with Edit > Reformat.

**Comment by ngn** [comment]
There's Preferences>Shortcuts>RD which you can map to a key combination of your choice but it uses RIDE's own formatting - not 100% compatible with the interpreter's.
See also #68

**Comment by mbaas2** [comment]
Ok. But, to be honest, it is not really userfriendly (IMHO) to "hide" such functionality in a shortcuts-table somewhere. Can't we have a proper menu which would expose these functions (and possibly even indicate the key-combination that had been assigned to it?)

**Comment by ngn** [comment]
You can add
```  Format            =RD```
somewhere in Preferences>Menu and restart RIDE.
I have no comment on whether that should be the default.

**Comment by geoffstreeter** [comment]
<RD> from the keyboard does not work. I should not need to mess with preferences for it to do so.

**Comment by jayfoad** [comment]
RIDE should probably copy the ODE's default key binding for RD, which is numeric-keypad-/. Currently RIDE's keyboard shortcut system does not distinguish numeric-keypad-/ from normal /, so it would need a bit of work.

**Comment by geoffstreeter** [comment]
RIDE should at least honour the users keyboard so that RD (UF819) works. How 
the unicode UF819 is generated is not the point - if that code reaches RIDE it 
should honour it as if RD was requested. Similarly, for any other codes on 
that page that are relevant.

**Comment by jayfoad** [comment]
> RIDE should at least honour the users keyboard so that RD (UF819) works

No, as a design decision RIDE does not respond to these Dyalog private-use-area command codes.

**Comment by geoffstreeter** [comment]
I have no recollection of being involved in such a decision. I would have 
strongly objected. It makes the Linux keyboard inappropriate with RIDE which 
seems like a backward step.

**Comment by e9gille** [comment]
I have just looked into this and found that the module we use (CodeMirror) is natively not distinguishing between numpad keys and their equivalents.

I've found a way top extend it to do exactly that and set the default shortcut to match the ODE (NumpadDivide). Together with 0eda47c7214de789cc851410a744323eba7124b0 this should now work as requested.

**Comment by ngn** [comment]
CodeMirror has two ways to define a mapping: as a combination of keys or as a character.
https://codemirror.net/doc/manual.html#keymaps
Prefs>Shortcuts maps keys.
Separately from that, RIDE has built-in knowledge of Dyalog's private-range Unicode chars and accepts them:
https://github.com/Dyalog/ride/blob/167f1aa6f75189bf7f9e19c1ff888f3d1dc02782/src/km.js#L353
(If you adopt a policy of not supporting the private range, I think that code should be removed.)
However, due to a bug in Chromium, some special key combinations don't produce characters - Chromium hijacks them before xkb has a chance to process them, and they never reach CodeMirror/RIDE. See https://bugs.chromium.org/p/chromium/issues/detail?id=485528#c14

**Comment by jayfoad** [comment]
> Separately from that, RIDE maps Dyalog's private-range Unicode chars:
> https://github.com/Dyalog/ride/blob/167f1aa6f75189bf7f9e19c1ff888f3d1dc02782/src/km.js#L353

Thanks @ngn. I didn't know about that.
