### ISSUE TITLE
MacOS Application menu should say "RIDE" (not "Dyalog-X.Y")

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#966]
### Describe the issue you are having
MacOS Application menu should say "RIDE", not "Dyalog", because, once started, RIDE can launch or connect to various versions of interpreter, without the application menu name changing. Indeed, RIDE can be open on its own (e.g. to change settings).

### Paste the contents of Help → About (Shift+F1)
```
4.5.3770
```

**Comment by abrudz** [comment]
The configuration should reflect that the name of the first menu is static. If it isn't possible to populate it with the actual app name, maybe use something like `<app-menu>` as placeholder.

**Comment by JasonRivers** [comment]
I don't know that I agree here.

The Ride Stand-alone application should indeed say Ride, That should be true today (if not that is indeed an issue).
The baked-in version as part of Dyalog (E.G. Dyalog-18.2) should say Dyalog-18.2, perhaps should have some additional Ride features (connecting to another interpreter) disabled to make it clearer.

But this was an intentional decision for the baked-in Dyalog/Ride.

**Comment by xpqz** [comment]
The RIDE stand-alone release says RIDE-X.Y. There are two aspects here:

1. On MacOS, the unholy duality of Dyalog-vs-RIDE. We understand how we got there. This is a decision that Dyalog should make if we carry on like that, or if we go down the Dyalog-on-Linux path, or provide both a separated install and a bundled.
2. The using of version numbers in the app name on MacOS -- no other Mac application does this. As a Mac user, this is grating.
![Screenshot 2023-07-26 at 11 23 02](https://github.com/Dyalog/ride/assets/2690852/27570109-610b-463f-a5fb-9d13c7918183)

**Comment by JasonRivers** [comment]
The version number - at least for Dyalog - is due to installing multiple versions, you would not be able to install both 18.2 & 19.0 if it was just named "Dyalog" as one would overwrite the other due to the way "Applications" work in the `/Applications` directory.

This is important for a number of users to be able run multiple versions.

For Ride standalone, this may be less of an issue We may be able to drop the version number on the Application without too many issues, However I don't have too many opinions on what we do there, that may be one for @dyaandys

**Comment by xpqz** [comment]
This is where having an unbundled approach would solve all problems, right ;) -- multiple interpreters installed under (say) `/opt/`. Single RIDE in `/Applications`. This is how Mathematica solves this problem, for example.

This is probably not the right place for this discussion -- but it sounds like we largely agree that RIDE-standalone doesn't need version numbers in its app name?

**Comment by aplteam** [comment]
> This is probably not the right place for this discussion -- but it sounds
like we largely agree that RIDE-standalone doesn't need version numbers in
its app name?

Well, I certainly need multiple versions of Ride as well.

Stefan, I noticed that all other applications in your list are not
programming languages. I wouldn't be too surprised if, say, Python would
have a version number as well.

**Comment by xpqz** [comment]
@aplteam -- I think that's partly my point -- no other _programming language_ installs itself under /Applications, thus bypassing the issue we face as the system intended. I have a gazillion versions of Python, Ruby, Go [etc] installed, none of which are troubling the /Applications directory. The closest think I can think of that is similar to Dyalog/RIDE is Mathematica which installs its front end into /Applications, and its kernels (the actual interpreter) elsewhere -- the "app" has no version as part of its installed name, but the kernels are carefully versioned. 

![Screenshot 2023-07-26 at 17 13 25](https://github.com/Dyalog/ride/assets/2690852/23423cee-e28a-4604-8fcf-bf573e8ef0f5)

I can't think of any app that installs in /Applications that uses version numbers as part of the application name. Happy to be shown examples.

**Comment by e9gille** [comment]
> Well, I certainly need multiple versions of Ride as well.

@aplteam  Can you tell me more about the use case here?

**Comment by e9gille** [comment]
Won't fix in RIDE but will be resolved when Dyalog not packaged with RIDE anymore.
